- hosts: all
  tasks:
  - name: "Copying jdk to managed node"
    copy:
      dest: "/"
      src: "jdk-8u171-linux-x64.rpm"
  - name: "Copying hadoop to managed node"
    copy:
      dest: "/"
      src: "hadoop-1.2.1-1.x86_64.rpm"
  - name: "Installing jdk"
    command: "rpm -i /jdk-8u171-linux-x64.rpm"
  - name: "Installing hadoop"
    command: "rpm -i /hadoop-1.2.1-1.x86_64.rpm --force"



